obstacle_range: 2.5 # means that the robot will only update its map with information about obstacles that are within 2.5 meters of the base
raytrace_range: 1.5 # Setting it to 3.0 meters as we have above means that the robot will attempt to clear out space in front of it up to 3.0 meters away given a sensor reading.
footprint: [[-.1626, .1143], [.1626, .1143], [.1626, -.1143], [-.1626, -.1143]]
#robot_radius: ir_of_robot
inflation_radius: 0.35 # setting the inflation radius at 0.55 meters means that the robot will treat all paths that stay 0.55 meters or more away from obstacles as having equal obstacle cost

observation_sources: scan scan_matched_points2
 # apparently we publish this

scan: {sensor_frame: map, data_type: LaserScan, topic: scan, marking: true, clearing: true}

scan_matched_points2: {sensor_frame: map, data_type: PointCloud2, topic: scan_matched_points2, marking: true, clearing: true}